package com.kiroule.vaadin.bakeryapp.ui.views.orderedit;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.testbench.elements.CssLayoutElement;
import com.vaadin.testbench.elements.VerticalLayoutElement;
import com.vaadin.testbench.elementsbase.ServerClass;

@ServerClass("com.kiroule.vaadin.bakeryapp.ui.views.orderedit.OrderHistoryDesign")
@AutoGenerated
public class OrderHistoryDesignElement extends VerticalLayoutElement {

	public CssLayoutElement getItems() {
		return $(com.vaadin.testbench.elements.CssLayoutElement.class).id("items");
	}

}